#!/bin/bash
if [ -z "$BKNIXDIR" ]; then echo "Undefined: BKNIXDIR" >&2 ; exit 1; fi
PHPFPM_BASE="$BKNIXDIR/var/php-fpm"

echo Start php-fpm


if [ ! -e "$PHPFPM_BASE" ]; then
  echo "($PROG) Initialize php-fpm config ($PHPFPM_BASE)"
  mkdir -p "$PHPFPM_BASE"
fi
cat "$BKNIXDIR/etc/php-fpm.conf.tmpl" | sed "s;%%BKNIXDIR%%;$BKNIXDIR;g" > "$PHPFPM_BASE/php-fpm.conf"

exec php-fpm -y "$PHPFPM_BASE/php-fpm.conf" --nodaemonize
