#!/bin/bash
BKNIXDIR=/Users/totten/bknix
HTTPD_BASE="$BKNIXDIR/var/httpd"
PROG=svc-httpd-run

  if [ ! -e "$HTTPD_BASE" ]; then
    echo "($PROG) Initialize httpd config ($HTTPD_BASE)"
    REALHTTPDIR=$(dirname $(dirname $(which httpd)))
    mkdir -p "$HTTPD_BASE" "$HTTPD_BASE/logs" "$HTTPD_BASE/conf" "$HTTPD_BASE/htdocs"
    if [ ! -f "$HTTPD_BASE/htdocs/index.html" ]; then
      echo "<html><body>mynix laceholder</body></html>" > "$HTTPD_BASE/htdocs/index.html"
    fi
    for SUBDIR in bin cgi-bin error icons modules ;do
      [ ! -e "$HTTPD_BASE/$SUBDIR" ] && ln -s "$REALHTTPDIR/$SUBDIR" "$HTTPD_BASE/$SUBDIR"
    done
  fi
  rsync -a "$BKNIXDIR/config/httpd/./" "$HTTPD_BASE/conf/./"
  cat "$BKNIXDIR/config/httpd/httpd.conf.tmpl" | sed "s;%%BKNIXDIR%%;$BKNIXDIR;g" >  "$HTTPD_BASE/conf/httpd.conf"


exec apachectl -d "$HTTPD_BASE" -DFOREGROUND
